spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        driver-class-name: org.postgresql.Driver
        username:
        password:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            database: postgresql

