const data2 = [
	{
		id: 0,
		depart: 'Krakow',
		arrive: 'Paris',
		departureDate: '23.11',
		returnDate: '23.11',
		stops: 0,
		airlines: 'Ryanair',
		price: '123,00',
	},
	{
		id: 1,
		depart: 'Krakow',
		arrive: 'Paris',
		departureDate: '23.11',
		returnDate: '23.11',
		stops: 0,
		airlines: 'Ryanair',
		price: '123,00',
	},
	{
		id: 2,
		depart: 'Krakow',
		arrive: 'Paris',
		departureDate: '23.11',
		returnDate: '23.11',
		stops: 0,
		airlines: 'Ryanair',
		price: '123,00',
	},
	{
		id: 3,
		depart: 'Krakow',
		arrive: 'Paris',
		departureDate: '23.11',
		returnDate: '23.11',
		stops: 0,
		airlines: 'Ryanair',
		price: '123,00',
	},
	{
		id: 4,
		depart: 'Krakow',
		arrive: 'Paris',
		departureDate: '23.11',
		returnDate: '23.11',
		stops: 0,
		airlines: 'Ryanair',
		price: '123,00',
	},
	{
		id: 5,
		depart: 'Krakow',
		arrive: 'Paris',
		departureDate: '23.11',
		returnDate: '23.11',
		stops: 0,
		airlines: 'Ryanair',
		price: '123,00',
	},
];

export default data2;
