const data = [
	{
		depart: 'Krakow',
		arrive: 'Paris',
		departureDate: '23.11',
		returnDate: '23.11',
		stops: 0,
		airlines: 'Ryanair',
		price: '123,00',
	},
	{
		depart: 'Krakow',
		arrive: 'Paris',
		departureDate: '23.11',
		returnDate: '23.11',
		stops: 0,
		airlines: 'Ryanair',
		price: '123,00',
	},
	{
		depart: 'Krakow',
		arrive: 'Paris',
		departureDate: '23.11',
		returnDate: '23.11',
		stops: 0,
		airlines: 'Ryanair',
		price: '123,00',
	},
	{
		depart: 'Krakow',
		arrive: 'Paris',
		departureDate: '23.11',
		returnDate: '23.11',
		stops: 0,
		airlines: 'Ryanair',
		price: '123,00',
	},
	{
		depart: 'Krakow',
		arrive: 'Paris',
		departureDate: '23.11',
		returnDate: '23.11',
		stops: 0,
		airlines: 'Ryanair',
		price: '123,00',
	},
	{
		depart: 'Krakow',
		arrive: 'Paris',
		departureDate: '23.11',
		returnDate: '23.11',
		stops: 0,
		airlines: 'Ryanair',
		price: '123,00',
	},
];

export default data;
