spring:
    rabbitmq:
        queue:
            name: pending
            json:
                name: pending_json
        exchange:
            name: pending_exchange
        routing:
            key: pending_routing_key
            json:
                key: pending_json_routing_key

        host: localhost
        port: 5672
        username: guest
        password: guest
    security:
        jwt:
          secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
          expiration-time: 3600000
        user:
            name: admin
            password: haslo
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        driver-class-name: org.postgresql.Driver
        username:
        password:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            database: postgresql
cookies:
    domain: localhost

domainRoot: http://localhost:3000


